import pandas as pd
import numpy as np
from src.Exception import CustomException
import sys

    
def save_object(file_path, obj):
    pass
   
